name: CI

on:
  schedule:
    - cron: '0 21 * * *'  # Runs daily at midnight UTC+3
  push:
    branches:
      - master

jobs:
  update-episode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script
      run: python eod.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/alielsokary/ThreatLevelMidnight-Backend.git
        git add eod.json
        git commit -m 'Update episode of the day'
        git push origin master
